# Generated by Django 4.2.23 on 2025-10-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='sstudyTime',
            field=models.FloatField(default=0),
        ),
    ]
