# Generated by Django 4.2.23 on 2025-10-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_lesson_sstudytime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='sstudyTime',
            new_name='studyTime',
        ),
    ]
